import type { SshConnectInput, SshConsoleState, SshFileEntry, SshServerStats } from '../host/types.ts'

export async function request<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(path, { ...init, cache: 'no-store' }); const payload = await response.json() as T & { error?: unknown }; if (!response.ok) { const error = new Error(typeof payload.error === 'string' ? payload.error : `HTTP ${response.status}`) as Error & { fingerprint?: string, code?: string }; const record = payload as unknown as { fingerprint?: unknown }; error.fingerprint = typeof record.fingerprint === 'string' ? record.fingerprint : undefined; error.code = typeof payload.error === 'string' ? payload.error : undefined; throw error }; return payload }
export function state(sessionId: string): Promise<SshConsoleState> { return request(`/dsh-withssh/state.json?sessionId=${encodeURIComponent(sessionId)}`) }
export function connect(input: SshConnectInput, confirmation = false): Promise<SshConsoleState> { return request(confirmation ? '/dsh-withssh/confirm-host.json' : '/dsh-withssh/connect.json', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }) }
export function disconnect(sessionId: string): Promise<{ status: string }> { return request('/dsh-withssh/disconnect.json', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sessionId }) }) }
export function input(sessionId: string, text: string, command?: string): Promise<{ status: string }> { return request('/dsh-withssh/input.json', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sessionId, text, ...(command === undefined ? {} : { command }) }) }) }
export function stats(sessionId: string): Promise<SshServerStats> { return request(`/dsh-withssh/stats.json?sessionId=${encodeURIComponent(sessionId)}`) }
export function files(sessionId: string, path = '.'): Promise<readonly SshFileEntry[]> { return request(`/dsh-withssh/files.json?sessionId=${encodeURIComponent(sessionId)}&path=${encodeURIComponent(path)}`) }
